# Generated by Django 4.2.1 on 2023-06-14 22:46

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin')),
                ('is_manajer', models.BooleanField(default=False, verbose_name='Manajer')),
                ('is_pegawai', models.BooleanField(default=False, verbose_name='Pegawai')),
                ('is_pelanggan', models.BooleanField(default=False, verbose_name='Pelanggan')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('Pagi', 'Pagi'), ('Siang', 'Siang'), ('Malam', 'Malam')], max_length=50)),
                ('jam_masuk', models.TimeField()),
                ('jam_keluar', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Kamar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_kamar', models.CharField(choices=[('VVIP', 'VVIP'), ('Executive Class', 'Executive Class'), ('Superior Room', 'Superior Room'), ('Deluxe Room', 'Deluxe Room'), ('Family Room', 'Family Room'), ('Single Room', 'Single Room')], max_length=50)),
                ('no_kamar', models.CharField(max_length=50)),
                ('kapasitas', models.IntegerField(null=True)),
                ('kasur', models.CharField(max_length=50, null=True)),
                ('fasilitas_lainnya', models.CharField(blank=True, max_length=255, null=True)),
                ('tarif', models.IntegerField(null=True)),
                ('gambar_kamar', models.ImageField(blank=True, null=True, upload_to='kamar_images')),
                ('status_kamar', models.CharField(choices=[('Full Booked', 'Full Booked'), ('Booked', 'Booked'), ('Empty Room', 'Empty Room')], default='Empty Room', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Keuangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('kategori', models.CharField(choices=[('pemasukan', 'Pemasukan'), ('pengeluaran', 'Pengeluaran')], max_length=100)),
                ('keterangan', models.TextField()),
                ('pemasukan', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pengeluaran', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('jenis_kelamin', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=50)),
                ('alamat', models.CharField(max_length=255)),
                ('posisi', models.CharField(max_length=255)),
                ('no_telepon', models.CharField(max_length=15)),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beranda.jadwal')),
            ],
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelanggan', models.CharField(max_length=255)),
                ('jenis_kelamin_pelanggan', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=50)),
                ('alamat_pelanggan', models.CharField(max_length=255)),
                ('no_telepon_pelanggan', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lupa_password_token', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Presensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('jam_masuk', models.TimeField(auto_now_add=True)),
                ('bukti_absen', models.ImageField(blank=True, null=True, upload_to='absen/')),
                ('status', models.CharField(max_length=50)),
                ('pegawai', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='beranda.pegawai')),
            ],
        ),
        migrations.CreateModel(
            name='Pemesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_checkin', models.DateField(default=datetime.date(2023, 6, 15))),
                ('tanggal_checkout', models.DateField()),
                ('pesanan_khusus', models.TextField(blank=True)),
                ('metode_pembayaran', models.CharField(choices=[('Transfer Via BRI', 'Transfer Via BRI'), ('Bayar Di Tempat', 'Bayar Di Tempat')], max_length=50)),
                ('jumlah_pembayaran', models.IntegerField(default=0, null=True)),
                ('no_kamar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beranda.kamar')),
                ('pelanggan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beranda.pelanggan')),
            ],
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pembayaran', models.DateField(auto_now_add=True)),
                ('bukti_pembayaran', models.ImageField(null=True, upload_to='bukti_pembayaran/')),
                ('status_pembayaran', models.CharField(choices=[('Lunas', 'Lunas'), ('Belum Dibayar', 'Belum Dibayar')], default='Belum Dibayar', max_length=50)),
                ('pemesanan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beranda.pemesanan')),
            ],
        ),
    ]
