# Generated by Django 4.2.1 on 2023-06-15 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelanggan',
            name='no_telepon_pelanggan',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Hanya angka yang diperbolehkan')]),
        ),
    ]
