# Generated by Django 4.2.1 on 2023-06-15 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0002_alter_pelanggan_no_telepon_pelanggan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawai',
            name='no_telepon',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Hanya angka yang diperbolehkan')]),
        ),
    ]
