# Generated by Django 4.2.1 on 2023-06-16 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0004_alter_pemesanan_tanggal_checkin_notifikasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengeluaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pengeluaran', models.DateField()),
                ('keterangan_pengeluaran', models.CharField(max_length=255)),
                ('jumlah_pengeluaran', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='keuangan',
            name='pemasukan',
        ),
        migrations.AddField(
            model_name='keuangan',
            name='pembayaran',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beranda.pembayaran'),
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='jumlah_pembayaran',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='keuangan',
            name='pengeluaran',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beranda.pengeluaran'),
        ),
    ]
