# Generated by Django 4.2.1 on 2023-06-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0005_pengeluaran_remove_keuangan_pemasukan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemesanan',
            name='status_konfirmasi',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Disetujui', 'Disetujui'), ('Ditolak', 'Ditolak')], default='pending', max_length=20),
        ),
    ]
