# Generated by Django 4.2.1 on 2023-06-18 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0007_nomor_kamar_remove_kamar_jenis_kamar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kamar',
            old_name='nomor_kamar',
            new_name='jenis_kamar',
        ),
    ]
