# Generated by Django 4.2.1 on 2023-06-18 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0009_pemesanan_no_kamar_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pembayaran',
            old_name='status_konfirmasi',
            new_name='status_konfirmasi_pembayaran',
        ),
    ]
