# Generated by Django 4.2.1 on 2023-06-20 18:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0011_alter_nomor_kamar_jenis_kamar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemesanan',
            name='tanggal_checkin',
            field=models.DateField(default=datetime.date(2023, 6, 21)),
        ),
        migrations.CreateModel(
            name='Kunci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ktp_status', models.CharField(choices=[('submitted', 'Submitted'), ('not_submitted', 'Not Submitted')], default='not_submitted', max_length=15)),
                ('kunci_status', models.CharField(choices=[('delivered', 'Delivered'), ('not_delivered', 'Not Delivered')], default='not_delivered', max_length=15)),
                ('waktu_input', models.DateTimeField(auto_now_add=True)),
                ('pelanggan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beranda.pelanggan')),
                ('pemesanan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beranda.pemesanan')),
            ],
        ),
    ]
