# Generated by Django 4.2.1 on 2023-06-20 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0013_pelanggan_foto_ktp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pemesanan',
            name='pesanan_khusus',
        ),
    ]
