# Generated by Django 4.2.1 on 2023-06-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0015_pemesanan_id_pemesanan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemesanan',
            name='id_pemesanan',
            field=models.CharField(default='56LIU', editable=False, max_length=50),
        ),
    ]
