# Generated by Django 4.2.1 on 2023-06-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0016_alter_pemesanan_id_pemesanan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembayaran',
            name='id_pembayaran',
            field=models.CharField(default='ITF5MFYUZ1', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='id_pemesanan',
            field=models.CharField(default='NK6S78EP2F', editable=False, max_length=50),
        ),
    ]
