# Generated by Django 4.2.1 on 2023-06-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0017_pembayaran_id_pembayaran_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembayaran',
            name='id_pembayaran',
        ),
        migrations.AddField(
            model_name='pemesanan',
            name='id_pembayaran',
            field=models.CharField(default='J0S4SUOXFI', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='id_pemesanan',
            field=models.CharField(default='EFV5HXI7OF', editable=False, max_length=50),
        ),
    ]
