# Generated by Django 4.2.1 on 2023-06-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0018_remove_pembayaran_id_pembayaran_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelanggan',
            name='foto_pelanggan',
            field=models.ImageField(blank=True, null=True, upload_to='pelanggan_images'),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='id_pembayaran',
            field=models.CharField(default='QNY1VTIRWJ', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='id_pemesanan',
            field=models.CharField(default='DJIHPJGAM9', editable=False, max_length=50),
        ),
    ]
