# Generated by Django 4.2.1 on 2023-06-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0019_pelanggan_foto_pelanggan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_manajer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_pegawai',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_pelanggan',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Pelanggan', 'Pelanggan'), ('Pegawai', 'Pegawai'), ('Manajer', 'Manajer')], default=12345, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='id_pembayaran',
            field=models.CharField(default='U5GDGVX29D', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='id_pemesanan',
            field=models.CharField(default='UUT9B0ZDHR', editable=False, max_length=50),
        ),
    ]
