# Generated by Django 4.2.1 on 2023-06-21 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0020_remove_user_is_admin_remove_user_is_manajer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelanggan',
            name='user',
            field=models.OneToOneField(default=12345, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='id_pembayaran',
            field=models.CharField(default='VFPQXXQFII', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='id_pemesanan',
            field=models.CharField(default='R53AYZFZUH', editable=False, max_length=50),
        ),
    ]
