# Generated by Django 4.2.1 on 2023-06-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0021_pelanggan_user_alter_pemesanan_id_pembayaran_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelanggan',
            name='user',
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='id_pembayaran',
            field=models.CharField(default='XDHAEBBFAR', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='id_pemesanan',
            field=models.CharField(default='AUES8F88OV', editable=False, max_length=50),
        ),
    ]
