# Generated by Django 4.2.1 on 2023-06-21 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0022_remove_pelanggan_user_alter_pemesanan_id_pembayaran_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelanggan',
            name='foto_pelanggan',
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='id_pembayaran',
            field=models.CharField(default='BO5OUJN50W', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='id_pemesanan',
            field=models.CharField(default='2AOFU1LZS5', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='tanggal_checkin',
            field=models.DateField(default=datetime.date(2023, 6, 22)),
        ),
    ]
