# Generated by Django 4.2.1 on 2023-06-21 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0024_user_status_alter_pemesanan_id_pembayaran_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengeluaran',
            name='pembayaran',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beranda.pembayaran'),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='id_pembayaran',
            field=models.CharField(default='U6A67RNTSP', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='id_pemesanan',
            field=models.CharField(default='YM3QVIOF1K', editable=False, max_length=50),
        ),
    ]
