# Generated by Django 4.2.1 on 2023-06-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0025_pengeluaran_pembayaran_alter_pemesanan_id_pembayaran_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kunci',
            name='pelanggan',
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='id_pembayaran',
            field=models.CharField(default='B2LJB947BD', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='id_pemesanan',
            field=models.CharField(default='MIGB0C8R1G', editable=False, max_length=50),
        ),
    ]
