# Generated by Django 4.2.1 on 2023-06-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0026_remove_kunci_pelanggan_alter_pemesanan_id_pembayaran_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presensi',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='id_pembayaran',
            field=models.CharField(default='ZNU8H4HGAY', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='id_pemesanan',
            field=models.CharField(default='0THLB0YHQ9', editable=False, max_length=50),
        ),
    ]
