# Generated by Django 4.2.1 on 2023-06-23 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0027_presensi_url_alter_pemesanan_id_pembayaran_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemesanan',
            name='id_pembayaran',
            field=models.CharField(default='SX9VRAZ6K8', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='id_pemesanan',
            field=models.CharField(default='OD5OFY3QDM', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='tanggal_checkin',
            field=models.DateField(default=datetime.date(2023, 6, 23)),
        ),
    ]
