# Generated by Django 4.2.1 on 2023-06-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0028_alter_pemesanan_id_pembayaran_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemesanan',
            name='id_pembayaran',
            field=models.CharField(default='WNU6P64XCN', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='id_pemesanan',
            field=models.CharField(default='V9IM2KJGED', editable=False, max_length=50),
        ),
    ]
