# Generated by Django 4.2.1 on 2023-07-09 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0030_pelanggan_tanggal_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelanggan',
            name='tanggal_input',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='tanggal_checkin',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 20, 43, 55, 209558, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='tanggal_checkout',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 20, 43, 55, 209558, tzinfo=datetime.timezone.utc)),
        ),
    ]
