# Generated by Django 4.2.1 on 2023-07-10 20:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0032_notification_alter_pemesanan_tanggal_checkin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='pemesanan',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='beranda.pemesanan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='tanggal_checkin',
            field=models.DateField(default=datetime.datetime(2023, 7, 10, 20, 28, 50, 226219, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='tanggal_checkout',
            field=models.DateField(default=datetime.datetime(2023, 7, 10, 20, 28, 50, 226219, tzinfo=datetime.timezone.utc)),
        ),
    ]
