# Generated by Django 4.2.1 on 2023-07-10 21:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0034_remove_notification_pemesanan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='pemesanan',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='beranda.pemesanan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='tanggal_checkin',
            field=models.DateField(default=datetime.datetime(2023, 7, 10, 21, 17, 18, 980935, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='tanggal_checkout',
            field=models.DateField(default=datetime.datetime(2023, 7, 10, 21, 17, 18, 980935, tzinfo=datetime.timezone.utc)),
        ),
    ]
