# Generated by Django 4.2.1 on 2023-07-10 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0035_notification_pemesanan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemesanan',
            name='tanggal_checkin',
            field=models.DateField(default=datetime.datetime(2023, 7, 10, 22, 0, 1, 257741, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='tanggal_checkout',
            field=models.DateField(default=datetime.datetime(2023, 7, 10, 22, 0, 1, 257741, tzinfo=datetime.timezone.utc)),
        ),
    ]
