# Generated by Django 4.2.1 on 2023-07-11 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0037_alter_pemesanan_tanggal_checkin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemesanan',
            name='tanggal_checkin',
            field=models.DateField(default=datetime.datetime(2023, 7, 11, 0, 44, 19, 900068, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='tanggal_checkout',
            field=models.DateField(default=datetime.datetime(2023, 7, 11, 0, 44, 19, 900068, tzinfo=datetime.timezone.utc)),
        ),
    ]
