# Generated by Django 4.2.1 on 2023-08-12 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0039_alter_pemesanan_tanggal_checkin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemesanan',
            name='status_kamar',
            field=models.CharField(choices=[('Empty Room', 'Empty Room'), ('Booked', 'Booked')], default='Empty Room', max_length=20),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='tanggal_checkin',
            field=models.DateField(default=datetime.datetime(2023, 8, 12, 18, 48, 46, 941616, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='tanggal_checkout',
            field=models.DateField(default=datetime.datetime(2023, 8, 12, 18, 48, 46, 941616, tzinfo=datetime.timezone.utc)),
        ),
    ]
