# Generated by Django 4.2.1 on 2023-08-13 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0040_pemesanan_status_kamar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomor_kamar',
            name='status_kamar',
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='status_kamar',
            field=models.CharField(choices=[('Full Booked', 'Full Booked'), ('Booked', 'Booked'), ('Empty Room', 'Empty Room')], default='Empty Room', max_length=20),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='tanggal_checkin',
            field=models.DateField(default=datetime.datetime(2023, 8, 13, 11, 5, 20, 298232, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='tanggal_checkout',
            field=models.DateField(default=datetime.datetime(2023, 8, 13, 11, 5, 20, 298232, tzinfo=datetime.timezone.utc)),
        ),
    ]
