# Generated by Django 4.2.1 on 2023-08-13 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0042_remove_pemesanan_pelanggan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemesanan',
            name='tanggal_input',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='tanggal_checkin',
            field=models.DateField(default=datetime.datetime(2023, 8, 13, 11, 56, 56, 528658, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='tanggal_checkout',
            field=models.DateField(default=datetime.datetime(2023, 8, 13, 11, 56, 56, 528658, tzinfo=datetime.timezone.utc)),
        ),
    ]
