# Generated by Django 4.2.1 on 2023-08-13 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0043_pemesanan_tanggal_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemesanan',
            name='foto_ktp',
            field=models.ImageField(blank=True, null=True, upload_to='foto_ktp'),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='tanggal_checkin',
            field=models.DateField(default=datetime.datetime(2023, 8, 13, 17, 36, 38, 486417, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='tanggal_checkout',
            field=models.DateField(default=datetime.datetime(2023, 8, 13, 17, 36, 38, 486417, tzinfo=datetime.timezone.utc)),
        ),
    ]
